"""Shared helpers for the WP-7.1 identity-resolution tests (unique module
name — safe for combined collection with the capture/reconstruction/extraction/
normalization/derivation/validation/validation_domain/canonicalization/
canonical_assembly suites)."""
import sys
from pathlib import Path

SRC = Path(__file__).resolve().parent.parent.parent          # tests → identity_resolution → src
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

VAL_TESTS = SRC / "validation" / "tests"
if str(VAL_TESTS) not in sys.path:
    sys.path.insert(0, str(VAL_TESTS))

VSM_TESTS = SRC / "validation_domain" / "tests"
if str(VSM_TESTS) not in sys.path:
    sys.path.insert(0, str(VSM_TESTS))

from capture import S1Service  # noqa: E402  (P5.1/P5.2 helpers reused verbatim)
from val_helpers import (      # noqa: E402
    FORMULA,
    PAGE_OK,
    R_CONSIST,
    R_PRESENT,
    R_ROUNDED,
    R_TOLERANCE,
    TOLERANCE,
    PRECISION,
    MODE,
    ValidationStack,
)
from vsm_helpers import (      # noqa: E402
    ValidationDomainStack,
    REF_KEYS,
    exact_probe_rule,
    nonexact_probe_rule,
    tolerance_probe_rule,
)
from identity_resolution import (  # noqa: E402
    IdentityDefiniteDuplicate,
    IdentityInputIntegrityFailure,
    IdentityReadSuccess,
    IdentityReplay,
    IdentityRequestRefused,
    IdentityResolutionRecorded,
    IdentityResolutionService,
    IdentityResolutionStore,
    IdentityStorageUnavailable,
    ORIGIN_HOLOO_CAPTURE,
    ORIGIN_KANDOO_SALE,
    ORIGIN_OTHER_POS_CAPTURE,
)

# Identity test corpus — the S2 triad rides on distinct, deterministic fields.
# invoice.number → text; invoice.date → date; total.net → decimal (extracted;
# D-02 "کاملاً استخراج" admits EXTRACTED only — the verified WP-4.1 read is
# the only value path). All three come out NORMALIZED in the verified read.

_PAGE_SEQ = {"n": 1000}
_LAST = {"number": None}


def unique_ir_pages(total_net="1000.00", tax="80", extra=""):
    """Distinct identity pages (unique invoice number) — each call produces a
    different capture S1, so multiple states can coexist in one test."""
    _PAGE_SEQ["n"] += 1
    number = f"INV-IR-{_PAGE_SEQ['n']:04d}"
    _LAST["number"] = number
    return [f"invoice.number={number}\n"
            f"invoice.date=2026-10-08\n"
            f"total.net={total_net}\ntax.amount={tax}\n{extra}"
            .encode("utf-8")]


def twin_pages(number=None, date="2026-10-08",
               total_net="1000.00", tax="80"):
    """A DIFFERENT byte ordering of ONE identity — different capture S1, same
    exact S2 values (the D-03 duplicate corpus). By default the LAST number
    generated by unique_ir_pages() is reused."""
    number = number or _LAST["number"] or "INV-IR-1001"
    return [f"total.net={total_net}\ntax.amount={tax}\n"
            f"invoice.date={date}\ninvoice.number={number}\n"
            .encode("utf-8")]


def third_order_pages(number=None, date="2026-10-08",
                      total_net="1000.00", tax="80"):
    """A third byte ordering of the SAME identity values."""
    number = number or _LAST["number"] or "INV-IR-1001"
    return [f"tax.amount={tax}\ninvoice.number={number}\n"
            f"total.net={total_net}\ninvoice.date={date}\n"
            .encode("utf-8")]


def no_number_pages():
    """invoice.number present but EMPTY → the role has no usable value
    (OD-G2: empty strings are not usable identity values)."""
    return [b"invoice.number=\ninvoice.date=2026-10-08\n"
            b"total.net=300.00\ntax.amount=24\n"]


def ambiguous_number_pages():
    return [b"invoice.number=INV-AMBIG-A\ninvoice.number=INV-AMBIG-B\n"
            b"invoice.date=2026-10-08\ntotal.net=750.00\ntax.amount=60\n"]


def ambiguous_date_pages():
    return [b"invoice.number=INV-AMBIG-D\ninvoice.date=2026-10-08\n"
            b"invoice.date=2026-10-09\ntotal.net=750.00\ntax.amount=60\n"]


def ambiguous_total_role_pages():
    """Two candidates on the field bound to INVOICE_TOTAL (seller.vat — a
    text field the reference rules never constrain)."""
    return [b"invoice.number=INV-AMBIG-T\ninvoice.date=2026-10-08\n"
            b"total.net=750.00\ntax.amount=60\nseller.vat=VA\n"
            b"seller.vat=VB\n"]


def one_char_diff_pages():
    """Case F corpus: identical to the LAST generated identity except ONE
    character of the exact invoice-number value."""
    base = _LAST["number"] or "INV-IR-1001"
    last = base[-1]
    flipped = str((int(last) + 1) % 10) if last.isdigit() else "X"
    return twin_pages(number=base[:-1] + flipped)


def whitespace_pages():
    """Trailing whitespace inside one exact value (raw bytes differ; the
    frozen normalization owns whatever canonicalization applies)."""
    return [b"invoice.number=INV-IR-WS-1 \ninvoice.date=2026-10-08\n"
            b"total.net=1000.00\ntax.amount=80\n"]


def no_whitespace_pages():
    return [b"invoice.number=INV-IR-WS-1\ninvoice.date=2026-10-08\n"
            b"total.net=1000.00\ntax.amount=80\n"]


def absent_total_role_pages():
    """VALID state whose INVOICE_TOTAL-bound field (seller.vat) is absent →
    the role has 0 usable rows (d03-incomplete)."""
    return [b"invoice.number=INV-IR-ABSENT-T\ninvoice.date=2026-10-08\n"
            b"total.net=500.00\ntax.amount=40\n"]


# The declared identity binding — the frozen D-02 roles → source field names
# (same discipline as the P6.1 corpus: the total role binds the EXTRACTED
# total.net; seller.vat variants exercise role-level absence/ambiguity).
BINDING = {
    "INVOICE_NUMBER": "invoice.number",
    "INVOICE_DATE": "invoice.date",
    "INVOICE_TOTAL": "total.net",
}
BINDING_TOTAL_VIA_VAT = {
    "INVOICE_NUMBER": "invoice.number",
    "INVOICE_DATE": "invoice.date",
    "INVOICE_TOTAL": "seller.vat",
}


class IdentityResolutionStack(ValidationDomainStack):
    """The P5.2 composition PLUS the WP-7.1 identity store/service — the
    WP-7.1 stack under test. All test-declared probe rules are
    pre-registered by the P5.2 stack itself."""

    def __init__(self, capture_db, recon_db, extraction_db, binding_db,
                 norm_db, deriv_db, val_db, vsm_db, identity_db,
                 with_evidence=True, engines=None, rules=None,
                 extra_rules=(), formulas=None, norm_rulesets=None):
        super().__init__(capture_db, recon_db, extraction_db, binding_db,
                         norm_db, deriv_db, val_db, vsm_db,
                         with_evidence=with_evidence, engines=engines,
                         rules=rules, extra_rules=extra_rules,
                         formulas=formulas, norm_rulesets=norm_rulesets)
        self.identity_db = identity_db
        self.identity_store = IdentityResolutionStore(identity_db,
                                                      S1Service())
        self.identity = IdentityResolutionService(
            self.identity_store, self.vsm, self.norm, S1Service())

    # -- pipeline helpers --------------------------------------------------

    def build_valid_identity_state(self, parts=None, label="ir-test",
                                   ruleset_id="kandoo-ir-rules",
                                   ruleset_version="1", keys=None):
        """Full happy path: capture → … → VALID/CLEAR domain state over the
        complete reference ruleset, with the identity fields present.
        Returns (normalization_id, projection_outcome)."""
        nid = self.build_derived(
            unique_ir_pages() if parts is None else parts, label=label)
        self.validate_all_reference(nid)
        projection = self.project(nid, keys or REF_KEYS,
                                  ruleset_id=ruleset_id,
                                  ruleset_version=ruleset_version)
        return nid, projection

    def resolve_ok(self, domain_state_id, origin=ORIGIN_HOLOO_CAPTURE,
                   binding=None):
        outcome = self.identity.resolve(
            domain_state_id, origin,
            BINDING if binding is None else binding)
        assert isinstance(outcome, IdentityResolutionRecorded), outcome
        return outcome

    def close(self):
        self.identity_store.close()
        super().close()


# ---------------------------------------------------------------------------
# Non-VALID/CLEAR state builders (R1b corpus) — same probe mechanics as the
# P5.2/P6.1 suites (probe rules are pre-registered by ValidationDomainStack).
# ---------------------------------------------------------------------------

def decisive_invalid_state(stack, parts=None, label="ir-decisive"):
    """INVALID/REJECT state: exact probe rule decisively violated
    (SUB(net,net)=0 vs tax.amount=80)."""
    nid = stack.build_normalization(
        unique_ir_pages() if parts is None else parts, label=label)
    outcome = stack.val.validate(nid, "vsm-probe-exact-mismatch", "1")
    assert type(outcome).__name__ == "ValidationCompleted", outcome
    assert outcome.record.outcome == "INVALID"
    projection = stack.project(nid, [("vsm-probe-exact-mismatch", "1")],
                               ruleset_id="ir-decisive-rules")
    return nid, projection


def tolerance_invalid_state(stack, parts=None, label="ir-tolerance"):
    """INVALID/REVIEW state: D-08 tolerance mismatch (T2 route)."""
    nid = stack.build_normalization(
        unique_ir_pages() if parts is None else parts, label=label)
    outcome = stack.val.validate(nid, "vsm-probe-tolerance-mismatch", "1")
    assert type(outcome).__name__ == "ValidationCompleted", outcome
    assert outcome.record.outcome == "INVALID"
    assert outcome.record.outcome_reason == "mismatch-beyond-tolerance"
    projection = stack.project(nid, [("vsm-probe-tolerance-mismatch", "1")],
                               ruleset_id="ir-tolerance-rules")
    return nid, projection


def deferred_state(stack, parts=None, label="ir-deferred"):
    """DEFERRED/REVIEW state: non-exact intermediate (T4 route)."""
    if parts is None:
        _PAGE_SEQ["n"] += 1
        parts = [f"a=1.00\nb=3\nt=2.00\nz={_PAGE_SEQ['n']}\n"
                 .encode("utf-8")]
    nid = stack.build_normalization(parts, label=label)
    outcome = stack.val.validate(nid, "vsm-probe-nonexact", "1")
    assert type(outcome).__name__ == "ValidationCompleted", outcome
    projection = stack.project(nid, [("vsm-probe-nonexact", "1")],
                               ruleset_id="ir-deferred-rules")
    return nid, projection


def unresolved_state(stack, parts=None, label="ir-unresolved"):
    """UNRESOLVED/REVIEW state: D-01 order exhausted (T3 route) — the R2 rule
    input tax.amount has no usable EXTRACTED value and no DERIVED value."""
    if parts is None:
        _PAGE_SEQ["n"] += 1
        parts = [f"total.net=1000.00\nz={_PAGE_SEQ['n']}\n"
                 .encode("utf-8")]
    nid = stack.build_normalization(parts, label=label)
    outcome = stack.val.validate(nid, R_TOLERANCE, "1")
    assert type(outcome).__name__ == "ValidationCompleted", outcome
    projection = stack.project(nid, [(R_TOLERANCE, "1")],
                               ruleset_id="ir-unresolved-rules")
    return nid, projection


def read_verified(stack, domain_state_id):
    """The verified read of a resolution for assertions."""
    outcome = stack.identity.resolve(domain_state_id, ORIGIN_HOLOO_CAPTURE,
                                     BINDING)
    return outcome


__all__ = [
    "FORMULA", "PAGE_OK", "R_CONSIST", "R_PRESENT", "R_ROUNDED",
    "R_TOLERANCE", "TOLERANCE", "PRECISION", "MODE",
    "ValidationStack", "ValidationDomainStack", "REF_KEYS",
    "exact_probe_rule", "nonexact_probe_rule", "tolerance_probe_rule",
    "IdentityResolutionStack", "IdentityResolutionStore",
    "IdentityResolutionService",
    "IdentityResolutionRecorded", "IdentityDefiniteDuplicate",
    "IdentityReplay", "IdentityReadSuccess", "IdentityRequestRefused",
    "IdentityInputIntegrityFailure", "IdentityStorageUnavailable",
    "ORIGIN_HOLOO_CAPTURE",
    "unique_ir_pages", "twin_pages", "third_order_pages",
    "no_number_pages", "ambiguous_number_pages", "ambiguous_date_pages",
    "ambiguous_total_role_pages", "one_char_diff_pages",
    "whitespace_pages", "no_whitespace_pages", "absent_total_role_pages",
    "BINDING", "BINDING_TOTAL_VIA_VAT",
    "decisive_invalid_state", "tolerance_invalid_state",
    "deferred_state", "unresolved_state", "read_verified",
]
